name: tpc_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  # replit uses version 2.13 so we downgrade sdk requirements to support it
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.0
  base_x: ^2.0.0
  crypto: ^3.0.2
  dart_ipify: ^1.1.1
  quiver: ^3.1.0
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
