name: tpc_server
# homepage: https://www.example.com
environment:
  # replit uses version 2.14.3 so we downgrade sdk requirements to support it
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  args: ^2.3.0
  base_x: ^2.0.0
  crypto: ^3.0.2
  dart_ipify: ^1.1.1
  lua_dardo: ^0.0.4
  path: ^1.8.2
  quiver: ^3.1.0
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1
  arrow_lang:
    git:
      url: https://github.com/IonutParau/arrow_lang
      ref: stable
  lua_vm_bindings:
    git:
      url: https://github.com/IonutParau/lua_vm_bindings
      ref: main

dev_dependencies:
  lints: ^1.0.0
