name: tpc_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  # replit uses version 2.12 so we downgrade sdk requirements to support it
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  crypto: ^3.0.2
  dart_ipify: ^1.1.1
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
