on: push

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/Windows.exe"
      - run: move "dlls\lua54.dll" "build\dlls\lua54.dll"
      - uses: actions/upload-artifact@v1
        with:
          name: WindowsExe
          path: build
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/Linux.ext"
      - run: mv dlls/liblua54.so build/dlls/liblua54.so
      - uses: actions/upload-artifact@v1
        with:
          name: LinuxExt
          path: build
  build_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: dart compile exe bin/main.dart -v -o "build/MacOS.ext"
      - run: mv dlls/liblua52.dylib build/dlls/liblua52.dylib
      - uses: actions/upload-artifact@v1
        with:
          name: MacOSExt
          path: build
